### ISSUE TITLE
Navigation between Question 1 and 2 fragments does not work.

### ISSUE THREAD

**Issue by ipshitaRB** [theDroidCamp/Qvid19#10]
Previous and Next button does not work in Question one @MriDx

**Comment by MriDx** [comment]
@ipshitaRB what is error ? Can you tell me if it is breaking ?

**Comment by ipshitaRB** [comment]
![question_one](https://user-images.githubusercontent.com/11401599/84705715-d62cc680-af29-11ea-8303-515233df176b.gif)

**Comment by MriDx** [comment]
@ipshitaRB if you are checking any app and if its breaking at some point then you should check logcat before creating an issue

**Comment by MriDx** [comment]
@ipshitaRB Let me tell you , when you are filling a from online in and if it has some check box to check only one, then you can change your selection infinite times unless you press submit or save your selection. The same flow I used here too.. When you you choose only correct answer, then pressing next will add your score, which will show on 2nd question fragment. And where should we suppose to send back user on previous pressed from first question ?? Do we have previous question from first question ??? No, we don't. Yeah I should've hide the previous link,that's my fault. And the app is breaking on question two fragment. Check your logcat. I reviews my codes before sending it anywhere. And for colors.. I just need to change colorAccent from my theme.

I hope you you get it. Or tell me if you have any confusion. 

Trust me I've already done this types of app two months ago 😁

**Comment by MriDx** [comment]
@ipshitaRB  i think the issue should mark as closed
